apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: server
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: web-server
          image: artkhud20/web-server:1.0.0
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /hello.html
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3