version: "3"

services:

  server:

    image: artkhud20/web-server:1.0.0
 
    build: 
      context: web-server/
      network: host

    ports:
      - 8000:8000

    user: "1001"

    network_mode: host

    healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:8000 || exit 1
        interval: 5s
        timeout: 5s
        retries: 5